// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjF3GsLJ_nYzOzl2AUVEkpi-rpilmDGlw',
    appId: '1:392902111868:web:5227f765e98b1a88bc4ff9',
    messagingSenderId: '392902111868',
    projectId: 'crush-5f8dc',
    authDomain: 'crush-5f8dc.firebaseapp.com',
    storageBucket: 'crush-5f8dc.appspot.com',
    measurementId: 'G-4Q2CZTNRPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwWD11CCBORi6oNPJeEDRJSa0MqYRARHs',
    appId: '1:392902111868:android:d336e3b3373c6fecbc4ff9',
    messagingSenderId: '392902111868',
    projectId: 'crush-5f8dc',
    storageBucket: 'crush-5f8dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0bFlr-OwPAjMWa3HutL7-psd41VzJOEQ',
    appId: '1:392902111868:ios:f883057ecc8b1e4abc4ff9',
    messagingSenderId: '392902111868',
    projectId: 'crush-5f8dc',
    storageBucket: 'crush-5f8dc.appspot.com',
    iosClientId:
        '392902111868-tbmudie2b3qq7ko1jtdro5l7h3jbu201.apps.googleusercontent.com',
    iosBundleId: 'com.zero.crushClient',
  );
}
